spring:
  data:
    mongodb:
      host: ${SPRING_DATASOURCE_HOST}
      port: ${SPRING_DATASOURCE_PORT}
      database: ${SPRING_DATASOURCE_DATABASE}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      authentication-database: ${SPRING_DATASOURCE_PASSWORD}

jwt-secret-key: ${JWT_SECRET_KEY}

server:
  port: ${SERVER_PORT}
